default:
	./maketemp.py variables.csv DRUP-???.feature

cleanfeat:
	rm DRUP-???.feature

cleantemp:
	rm DRUP-???-template.feature

clean:
	rm *.feature

move:
	mv *-template.feature ~/Testing-Automation/templates/

.PHONY: default clean
